### ISSUE TITLE
Not instance OAuth2\Server

### ISSUE THREAD

**Issue by shamanis** [zfcampus/zf-oauth2#102]
Why is the factory $this->getServiceLocator()->get('ZF\OAuth2\Service\OAuth2Server') returns  object ZF\OAuth2\Factory\OAuth2ServerInstanceFactory and an error occurs: "ZF\OAuth2\Factory\OAuth2ServerInstanceFactory::verifyResourceRequest()". 
Examining the code, I tried to do $this->server()->verifyResourceRequest() and I get error 500.

SOLVED: I'am replace $this->server on $server, and call $server()->verifyResourceRequest(). It work.

**Comment by weierophinney** [comment]
We made a change for 1.1 to allow per-API (vs per-application) authentication, which required that the factory for the OAuth2\Server return a factory (it's complicated). The point is that the service now returns a factory, which will in turn return the OAuth2\Server instance, which you already discovered.

One point to note: with that upgrade to 1.1, that instance may or may not be what you want. Read the zf-mvc-auth documentation to discover how to get named OAuth2 server instances.
