### ISSUE TITLE
Incorrect audience and issuer on JwtAccessToken

### ISSUE THREAD

**Issue by basz** [zfcampus/zf-oauth2#103]
There are several options we should set if we want the oauth server to work with json web tokens
```
'zf-oauth2' => [
   'grant_types' => [
      'jwt' => true,
   ],
   'audience' => $_SERVER['HTTP_HOST'],
   'options' => [
      'use_jwt_access_tokens' => true,
   ]
]
```
use_jwt_access_tokens will make the token factory create JWT tokens.

The audience option is supposed to create tokens with the 'aud' set to that value. That way tokens received can be quickly discarded when they are asserted against the wrong server by accident (my understanding atleast). However it seems the for creation the client_id is used. And this validation will always fail.

Therefore the only way to get this to work is to set the audience to the client_id, and thus use the entire oauth server for only one client_id.

I'm not sure is this is a problem with Apigility or the OAuth2 server. I'll post an issue there too...

example request to /oauth and resulting JWT payload
```
http POST https://myserver/oauth client_id=plhw-client client_secret=XXX redirect_uri=http%3A%2F%2Flocalhost%3A4200 grant_type=authorization_code code=8ce459d24d231b0bce1645baa9d4e4044f549ad2
```
gets
```
{"access_token":"header.payload.signature","expires_in":3600,"token_type":"bearer","scope":"","refresh_token":"447ed3606ac2c04128346f406e0d1f7fbb90be43"}
```
manually decoding the payload will yield something like
```
{"jti":"e5424a45b467ad334df368b518028410997ae3d6","iss":"","aud":"plhw-client","sub":5,"exp":1432155489,"iat":1432151889,"token_type":"bearer","scope":""}
```
but to assert the JWT with will fail because;

a. the issuer is empty but is required
b. the audience is set to the client_id and not the audience in the configuration

``` 
http POST https://myserver/oauth grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer assertion= header.payload.signature
```

**Comment by bshaffer** [comment]
@basz The "iss" should be set by the zend framework library when the `OAuth2\ResponseType\JwtAccessToken` class is created (see the [config argument](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/ResponseType/JwtAccessToken.php#L32))

The "aud" is set to the client ID because this audience is *different* from that set by a JWT used for the JWTBearer grant type. however, I agree this is incorrect. It should be blank or set to the resource server uri, and the client ID should be stored elsewhere.

Also, "id" should be "jti" [here](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/ResponseType/JwtAccessToken.php#L64).

**Comment by bshaffer** [comment]
According to the [jwt-spec](https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-4.1.3)

> The "aud" (audience) claim identifies the recipients that... [omitted for brevity] 
   Use of this claim is OPTIONAL.

I will make this field configurable in the oauth2 library, but otherwise it can be left blank. The spec also says this can be a string OR array of values.

**Comment by basz** [comment]
from [here](https://github.com/bshaffer/oauth2-server-php/blob/develop/src/OAuth2/GrantType/JwtBearer.php#L157)
```
// Check the audience if required to match
if (!isset($jwt['aud']) || ($jwt['aud'] != $this->audience)) {
    $response->setError(400, 'invalid_grant', "Invalid audience (aud)");
    return null;
}
```
that if statement does not make $jwt['aud'] optional even when the comment says so... :-)

i'm thinking
```
if (isset($jwt['aud']) && ($jwt['aud'] != $this->audience))
   then err
```

**Comment by bshaffer** [comment]
@basz you are confusing JwtBearer with JwtAccessToken. I am not suggesting allowing empty audiences for JwtBearer, as the JwtBearer spec *does* require it. However, using JWTs as access tokens does not.

**Comment by jguittard** [comment]
@basz Shall we close this issue as @basz seemed to have answered to your concern?
