### ISSUE TITLE
The storage configuration for OAuth2 is missing

### ISSUE THREAD

**Issue by TomHAnderson** [zfcampus/zf-oauth2#117]
Continuing the work of `zfcampus/zf-oauth2-doctrine` the latest code implements the adapter through services of oauth2 in zf-mvc-auth.  When an application is properly configured this module still insists on a valid `$config['zf-oauth2']['storage']` entry.  This should not be necessary when using a service based adapter.

For this global.php configuration:
```php
    return array(
        'zf-mvc-auth' => array(
            'authentication' => array(
                'map' => array(
                    'DbApi\\V1' => 'oauth2_doctrine',
                ),
            ),

            'authentication' => array(
                'adapters' => array(
                    'oauth2_doctrine' => array(
                        'adapter' => 'ZF\\MvcAuth\\Authentication\\OAuth2Adapter',
                        'storage' => array(
                            'storage' => 'oauth2.doctrineadapter.default',
                            'route' => '/oauth',
                        ),
                    ),
                ),
            ),
        ),

        'zf-oauth2' => array(
            'allow_implicit' => false, // default (set to true when you need to support browser-based or mobile apps)
            'access_lifetime' => 3600, // default (set a value in seconds for access tokens lifetime)
            'enforce_state'  => true,  // default
    //        'storage'        => 'oauth2.doctrineadapter.default',
        ),
    );
```

without a value for storage the title's exception is raised.  This can be easily duplicated by cloning https://github.com/API-Skeletons/doctrine-skeleton and following the instructions in the README.md file.

**Comment by viniciusgava** [comment]
I'm following this issue and I agree with @TomHAnderson, It is necessary this modification for the *zfcampus/zf-oauth2-doctrine* work.

**Comment by TomHAnderson** [comment]
In this exampe my route is `/oauth` which I think may be a route name and not uri.  So, to find this answer I found:  

https://github.com/zfcampus/zf-mvc-auth/blob/master/test/Factory/NamedOAuth2ServerFactoryTest.php#L46
```php
            'zf-mvc-auth' => [
                'authentication' => [
                    'adapters' => [
                        'test' => [
                            'adapter' => 'ZF\MvcAuth\Authentication\OAuth2Adapter',
                            'storage' => [
                                'storage' => 'ZFTest\OAuth2\TestAsset\MockAdapter',
                                'route'   => 'test',
                            ],
```

But the route test [and test 2] are not created in the unit tests.

**Comment by TomHAnderson** [comment]
The problem may be because I'm accessing the `oauth` route directly to obtain a `client_credentials` grant.  This approach  bypasses `zf-mvc-auth`and calls the controller directly which instantiates *a* default oauth client which expects storage to be set.  

https://github.com/zfcampus/zf-oauth2/blob/master/src/Factory/AuthControllerFactory.php#L26
```php
        $oauth2ServerFactory = $services->get('ZF\OAuth2\Service\OAuth2Server');
        if ($oauth2ServerFactory instanceof OAuth2Server) {
            $oauth2Server = $oauth2ServerFactory;
            $oauth2ServerFactory = function () use ($oauth2Server) {
                return $oauth2Server;
            };
        }
```

It seems to me that `zf-oauth` should only exist in support of `zf-mvc-auth` in which case the routes should be (dynamic?) based on the `zf-mvc-auth` configuration.

Which brings me to ask, what is the intended use of a route specified in `zf-mvc-auth` and is it a route which should be [almost?] the same as `oauth`, in which case. how can it not implement the default adapter `ZF\OAuth2\Service\OAuth2Server`?  

This may not be a bug because the service I'm trying to use isn't intended to be used directly like this.  So I think the solution to this is to show an example of **how** a `zf-mvc-auth` configured oauth storage with route should be accessed!

**Comment by TomHAnderson** [comment]
I created an application with two zf-oauth2-doctrine OAuth2 endpoints controlling different APIs.  zf-oauth2, this module, is ment to create one OAuth2 in the same way DoctrineORMModule is ment to create one entitymanager.  

This module can control the core work of OAuth2 as-is and I do not have reason to expect change in this module.
