### ISSUE TITLE
bshaffer oauth2 v1.8

### ISSUE THREAD

**Issue by Michal-sk** [zfcampus/zf-oauth2#123]
Would it be possible to update bshaffer to 1.8, there is a bugfix in there which gives otherwise a lot of headache: https://github.com/bshaffer/oauth2-server-php/pull/491

**Comment by jguittard** [comment]
I've submitted a PR for token revoke support. https://github.com/zfcampus/zf-oauth2/pull/122
It'll be reviewed and hopefully merged after ZendCon. 

Julien.

**Comment by Michal-sk** [comment]
Ok great, im just not completly sure that fix is already merged into 1.8

**Comment by stefanotorresi** [comment]
@Michal-sk you can just run "composer update" and it will pull to the latest 1.* bshaffer lib.

**Comment by weierophinney** [comment]
Fixed with #122
