### ISSUE TITLE
Please pull fix

### ISSUE THREAD

**Issue by chateaux** [zfcampus/zf-oauth2#137]
Hello,

Quite a few of us are waiting for this fix to be pulled:

https://github.com/zfcampus/zf-oauth2/pull/120#issuecomment-202807065

Thanks!

**Comment by klaudeclaw** [comment]
Bump

**Comment by dkmuir** [comment]
Looks like it's merged, but there's no new release yet? @ezimuel, can we get a working build please!

**Comment by MichaelGooden** [comment]
This still has not been released. I cannot see any blockers affecting this?
Ping @weierophinney @ezimuel

**Comment by MichaelGooden** [comment]
Fixed in https://github.com/zfcampus/zf-oauth2/releases/tag/1.3.2

(@chateaux please close this issue)
