### ISSUE TITLE
/resource test url with OPTIONS call

### ISSUE THREAD

**Issue by sariabod** [zfcampus/zf-oauth2#152]
Not sure if this is intended, but I ran into an issue creating a test app using reactjs. The library that was used sends a preflight OPTIONS call to the endpoint before attaching the bearer token. In this case, the OPTIONS call doesn't return any "allow" commands when calling the test resource (in my case /oauth/resource). This causes the call to fail with: 

```Response for preflight has invalid HTTP status code 401  ```

Shouldn't you be able to make an OPTIONS call without authenticating first?

**Comment by ezimuel** [comment]
@sariabod A request OPTIONS on a resource under authentication (like `/oauth/resource`) should be forbidden. You should be able to perform OPTIONS only on resource without authentication, like `/oauth`.

**Comment by sariabod** [comment]
@ezimuel Thank you for the clarification.
