### ISSUE TITLE
"user_id" is always null in authorization_code grant type

### ISSUE THREAD

**Issue by martinezdelariva** [zfcampus/zf-oauth2#40]
Using a `authorization_code` grant type:

`http://<apigility URL>/oauth/authorize?response_type=code
&client_id=testclient&redirect_uri=/oauth/receivecode&state=xyz&`**`user_id=user@domain.com`**

The parameter `user_id` is not store in DB  table _oauth_authorization_codes_ and then when request access code, the `user_id` is not populated to table `oauth_access_tokens`.

I think the issue could be that `ZF\OAuth2\Controller\AuthController::authorizeAction()`  when call `$this->server->handleAuthorizeRequest()` isn't use the fourth parameter.

Thanks.

**Comment by TomHAnderson** [comment]
@martinezdelariva This PR is related to user_id: https://github.com/zfcampus/zf-oauth2/pull/85
