### ISSUE TITLE
Mongo oAuth2 adapter 500 Internal Server Error

### ISSUE THREAD

**Issue by salerat** [zfcampus/zf-oauth2#50]
I have a problem. when i'm creating a Mongo oAuth2 adapter in Apigility admin panel i got 500 Internal Server Error
Request to /apigility/api/authentication/oauth2, json {database: "mongo_test" dsn_type: "Mongo" route_match: "/oauth"}
Error is Fatal error: Call to a member function isOAuth2() on a non-object in /path/vendor/zfcampus/zf-apigility-admin/src/Model/AuthenticationModel.php on line 53

How to fix this?

**Comment by mdjaman** [comment]
Issue with this config for mongodb any idea got exception An exception was raised while creating "ZF\OAuth2\Adapter\MongoAdapter"; no instance returned
```php
'db' => array(
    'dsn'      => 'mongodb://localhost:27017/qfriends_cloud', // for example "mysql:dbname=oauth2_db;host=localhost"
    'username' => 'root',
    'password' => '',
),
'allow_implicit' => true,
'access_lifetime' => 3600,
'enforce_state'  => true,  // default
'storage'        => 'ZF\OAuth2\Adapter\MongoAdapter',
