### ISSUE TITLE
Tables "oauth_refresh_tokens" and "oauth_authorization_codes" aren't populated with user_id on insert

### ISSUE THREAD

**Issue by tad3j** [zfcampus/zf-oauth2#59]
I've been trying to authenticate via "WEB-server application" scenario (PDO adapter), and all works well except of one thing, the user_id column doesn't get populated when refresh_tokens and authorization_codes are inserted into the DB.

It looks like that ->getQuery('user_id',null) doesn't return a user_id for cases mentioned above here, instead it returns null: https://github.com/zfcampus/zf-oauth2/blob/master/src/Controller/AuthController.php#L129 

Is this normal behavior? If so, is there a way to set user_id from an event, when row is being inserted?

**Comment by jguittard** [comment]
@tad3j can you close this issue?

**Comment by tad3j** [comment]
Sorry and thanks for reminding me. 

Looks like the code was already changed so link above points to wrong line. I'm going to close it although I am not able to test it ATM.
