### ISSUE TITLE
When using an expired access token, I'm getting 403 instead of 401

### ISSUE THREAD

**Issue by dorongutman** [zfcampus/zf-oauth2#69]
If I go to the sample /oauth/resource resource with an expired access token, I get a 401 "expired_token" message:

    {
        "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
        "title": "expired_token",
        "status": 401,
        "detail": "The access token provided has expired"
    }

However, if I go to my own "authentication required" REST service with the same expired expired access token, I get a 403 "forbidden" message:

    {
        "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
        "title": "Forbidden",
        "status": 403,
        "detail": "Forbidden"
    }

After some debugging, it seems that this is because the `$response` object that was passed to [OAuth2\Controller\ResourceController::verifyResourceRequest](https://github.com/bshaffer/oauth2-server-php/blob/v1.5/src/OAuth2/Controller/ResourceController.php#L41) (and later on set to 401 in [OAuth2\Controller\ResourceController::getAccessTokenData](https://github.com/bshaffer/oauth2-server-php/blob/v1.5/src/OAuth2/Controller/ResourceController.php#L86)) is just ignored later on in [ZF\MvcAuth\Authentication\DefaultAuthenticationListener::__invoke](https://github.com/zfcampus/zf-mvc-auth/blob/1.0.2/src/Authentication/DefaultAuthenticationListener.php#L174) (line 174 onwards) and a `GuestIdentity` is returned, causing the authentication to treat it as an un-authenticated request by a guest, and not as an expired_token request.

**Comment by dorongutman** [comment]
any updates on this ?

**Comment by prevostc** [comment]
Shouldn't we get 419 ?

**Comment by weierophinney** [comment]
@ezimuel Can you look into this one, please?

**Comment by danielhunt** [comment]
Any update on this?

**Comment by danielhunt** [comment]
From the looks of things, I'm going to have to hack in some sort of global state to account for a `419` here. Is there any knowledge for your side that will help with this or am I on my own?

Also worth noting that this bug makes this system effectively useless for any sort of production API that's used for the purposes of mobile and/or web apps - there's no way to know the difference between a `403 access denied` and a `403 invalid token` (which should be a `419` anyway)

**Comment by dorongutman** [comment]
Actually it needs to be a 401 as you have an option of "fixing" it by
login.

On Sunday, July 5, 2015, Daniel Hunt <notifications@github.com> wrote:

> From the looks of things, I'm going to have to hack in some sort of global
> state to account for a 419 here. Is there any knowledge for your side
> that will help with this or am I on my own?
>
> Also worth noting that this bug makes this system effectively useless for
> any sort of production API that's used for the purposes of mobile and/or
> web apps - there's no way to know the difference between a 403 access
> denied and a 403 invalid token (which should be a 419 anyway)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zfcampus/zf-oauth2/issues/69#issuecomment-118644462>.
>


-- 
Sent from a mobile thingy
Please excuse typos

**Comment by weierophinney** [comment]
This is fixed in zfcampus/zf-mvc-auth#83 — `ZF\MvcAuth\Adatper\OAuth2Adapter` now checks the response on OAuth2 validation failure to determine the type of failure, and returns a 401 if invalid credentials/tokens were provided, and a 403 if it was due to unauthorized scope.

**Comment by di-sysops** [comment]
Woot!
