### ISSUE TITLE
password salts?

### ISSUE THREAD

**Issue by EMCP** [zfcampus/zf-oauth2#74]
Not sure if this belongs more in the underlying OAuth2 server project, but is there any need / reason to salt the BCrypted passwords?

Could that be enabled/disabled via config?

**Comment by ezimuel** [comment]
For bcrypt we used [Zend\Crypt\Password\Bcrypt](http://framework.zend.com/manual/current/en/modules/zend.crypt.password.html#bcrypt) component that provides automatically a random salt for each hash. You don't need to provide salt manually.
