### ISSUE TITLE
oauth_scopes and type

### ISSUE THREAD

**Issue by iam-merlin** [zfcampus/zf-oauth2#81]
Hi,
simple question, what is the purpose of `type` in `oauth_scopes`? I saw that the default value is `supported` should I consider that there is only 2 values : `supported` / `unsupported` ? or this field is free to fill?

Thank you ^^

**Comment by coud** [comment]
I also don't get the client_id column purpose. The original table doesn't have this column. I can't find also where both type and client_id column is used in the codes. Can someone explain this?

**Comment by ezimuel** [comment]
@iam-merlin the `oauth_scopes` acts like a permission in OAuth2 scenario. Scope is used to limit the authorization granted to the client by the resource owner. For instance, in Facebook the scopes are used to limit the actions of a third-party application (“access basic information”, “post on wall”, etc).
The default value `supported` in the demo database is only an example, you can use all the values that you want.

You can find more information about the OAuth2 scopes [here](http://bshaffer.github.io/oauth2-server-php-docs/overview/scope/).

**Comment by ezimuel** [comment]
@iam-merlin the `type` in `oauth_scopes` was used in the old version of [bshaffer/oauth2-server-php](https://github.com/bshaffer/oauth2-server-php) to collect the scopes in group. We need to update the SQL schema of zf-oauth2 to use the new one reported [here](http://bshaffer.github.io/oauth2-server-php-docs/cookbook/).
@coud also the `client_id` column in `oauth_scopes` is a misprint from the old SQL schema.

**Comment by iam-merlin** [comment]
@ezimuel thx for the reply :+1:
