### ISSUE TITLE
Purpose of various tables

### ISSUE THREAD

**Issue by chateaux** [zfcampus/zf-oauth2#84]
Hello,

I am new to OAuth2 and am putting together my first app with ApiGility/ZF2. Where I am struggling is with my understanding of the various database tables. I am not sure where to store what. For instance http://coop.apps.knpuniversity.com has all the basic items, although the tutorial is for the user of the API and not for putting together the nuts and bolts of an app offering the API. I have however got some insight into how this should work.

So for instance: 

I want to be able to give clients access to my app. To do this an admin or a client may log in and setup an account, this account will be given access to the various end points as created in apiGility.

Step 1 is to create a unique client id which I do as such: $this->oAuthPdo->setClientDetails('testclient','$2y$14$f3qml4G2hG6sxM26VMq.geDYbsS089IBtVJ7DlD05BoViS9PFykE2','/oauth/receivecode');

This stores the details in the: oauth_clients table

From what I understand from the coop.app I can create scopes and link these scopes to a client. So my question is, how do I use oauth_scopes to limit the end points available to a client?

Many thanks!

**Comment by chateaux** [comment]
I added some visuals to StackOverflow: http://stackoverflow.com/questions/29123420/understanding-bshafers-oauth2-database-structure

Hope this is not a silly question.

**Comment by TomHAnderson** [comment]
Try this: https://raw.githubusercontent.com/zfcampus/zf-oauth2/4c3217c0e7fdddb2e254f44f88ad7fd8a2ef9083/media/OAuth2.skipper

You can open it with http://www.skipper18.com

My notes on your request:  
1. Your users are users not clients.  The client table is an application which can use the oauth2 service.  So users have clients.  Like if I have two facebook apps I am a user and each app is a client and facebook can authenticate another user against their login and grant an authorization code.

2. When scopes are related to a client that will be the default permissions granted from that client.   I hope this makes more sense after you get through 1.

**Comment by chateaux** [comment]
Thanks Tom, that does make sense now. Took me a bit of time.
