### ISSUE TITLE
PDO OAuth Throws exception

### ISSUE THREAD

**Issue by spectravp** [zfcampus/zf-oauth2#91]
Download latest apigility and vagrant up. Create a DB in the Vagrant environment and create a PDO adapter for OAuth in Apigility Admin.   Hit the OAuth api end point and you will get: "An exception was raised while creating \"ZF\\OAuth2\\Controller\\Auth\"; no instance returned"  Verified credentials are fine and can connect when instantiating an adapter manually. 

Further more, you will also see an exception 'The storage configuration [\'zf-oauth2\'][\'storage\'] for OAuth2 is missing' which is raised by OAuth2ServerFactory.   However, Apigility admin no longer creates the configuration using that array structure.

**Comment by spectravp** [comment]
If you provide the array configuration it is looking for, then you end up with a differing exception: Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for pdo

**Comment by sjwdavies** [comment]
Sorry to sound thick - but is this now resolved as I've just downloaded Apigility (I'm new to it) and get this error when trying to Authorise (using Postman) an OAuth2 connection:

"An exception was raised while creating "ZF\OAuth2\Controller\Auth"; no instance returned"

What gives - it's straight out of the box???

Thanks,
Steve

**Comment by agustincl** [comment]
Out of the box is working well, but @sjwdavies maybe you have another module with this line in the config file. Just remove it.

        'Zend\Authentication\AuthenticationService' => 'Zend\Authentication\AuthenticationService',
