### ISSUE TITLE
Only 2 params are passed to new instances of OAuth2/Server

### ISSUE THREAD

**Issue by danielhunt** [zfcampus/zf-oauth2#92]
https://github.com/zfcampus/zf-oauth2/blob/master/src/Factory/OAuth2ServerFactory.php#L76

Server instances are missing a `grantTypes` param, meaning that overriding isn't possible without replacing the factory completely.

**Comment by weierophinney** [comment]
This is going to be hard to implement, as we already have a top-level `grant_types` key under the `zf-oauth2` configuration. The values in there are used to enable or disable the various officially supported oauth2-server-php grant types, and are just `type => bool` pairs.

What *can* be done at this point, after #95 and zfcampus/zf-mvc-auth#71 are merged, is creation of a delegator factory to manually inject the grant types after instantiation:

```php
use Zend\ServiceManager\DelegatorFactoryInterface;
use Zend\ServiceManager\ServiceLocatorInterface;

class InjectGrantTypes implements DelegatorFactoryInterface
{
    public function createDelegatorWithName(
        ServiceLocatorInterface $services,
        $name,
        $requestedName,
        $callback
    ) {
        // Get the factory returned by the service
        $factory = $callback();

        // Invoke the factory and inject the custom grant type
        $server  = $factory(); // use the adapter-specific route if getting a per-API instance
        $server->addGrantType(
            $services->get('MyCustomGrantType')
        );

        // Return the factory
        return $factory;
    }
}
```

You would then register this with the service manager:

```php
array(
    'service_manager' => array(
        'delegators' => array(
            'ZF\OAuth2\Service\OAuth2Server` => array(
                'InjectGrantTypes',
            ),
        ),
    ),
)
```

While this is a bit more work, it accomplishes the goal, and will reduce confusion about potential configuration keys if we were to implement something in the zf-oauth2 and zf-mvc-auth factories.

**Comment by danielhunt** [comment]
Late response on this, but the explanation and example you gave worked perfectly.
Thanks for sorting this issue out.
